<<<<<<< HEAD
version: "3.8"

services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - live
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

=======
version: '3.8'

services:
>>>>>>> 69355aff134f4efa893df922943e88abcff70792
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
<<<<<<< HEAD
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"

=======
      - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
>>>>>>> 69355aff134f4efa893df922943e88abcff70792
    env_file:
      - ./.env
    depends_on:
      - db
<<<<<<< HEAD
    networks:
      - live
    links:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server"]
    networks:
      - live
=======

  db:
    image: postgres:14.5-alpine
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
>>>>>>> 69355aff134f4efa893df922943e88abcff70792

  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
<<<<<<< HEAD
      - ./src:/src
=======
      - ./app:/app
>>>>>>> 69355aff134f4efa893df922943e88abcff70792
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
<<<<<<< HEAD
    networks:
      - live

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: "celery -A app flower --address=0.0.0.0"
    depends_on:
      - celery
    networks:
      - live

volumes:
  pgdata:

networks:
  live:
=======
volumes:
  pgdata:
>>>>>>> 69355aff134f4efa893df922943e88abcff70792
