# Generated by Django 4.1.4 on 2022-12-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_id", models.IntegerField()),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=250)),
                ("link", models.URLField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "search_ad",
            },
        ),
        migrations.CreateModel(
            name="SponsoredAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_id", models.IntegerField()),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=250)),
                ("link", models.URLField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        default="default/sponsored_ad.jpg", upload_to="sponsored/"
                    ),
                ),
            ],
            options={
                "verbose_name": "sponsored_ad",
            },
        ),
    ]
