# Generated by Django 4.1.4 on 2022-12-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_searchadclicks_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchadclicks",
            name="advertisement_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="searchadimpression",
            name="advertisement_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sponsoredadclicks",
            name="advertisement_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sponsoredadimpression",
            name="advertisement_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
