# Generated by Django 4.1.4 on 2022-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_searchadclicks_advertisement_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchadclicks",
            name="clicks",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="searchadclicks",
            name="cpc",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="sponsoredadclicks",
            name="clicks",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sponsoredadclicks",
            name="cpc",
            field=models.FloatField(null=True),
        ),
    ]
