# Generated by Django 4.1.4 on 2022-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_sponsoredadimpression_cpi"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchadimpression",
            name="cpi",
            field=models.IntegerField(null=True),
        ),
    ]
