# Generated by Django 4.1.4 on 2022-12-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_searchadimpression_cpi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchadimpression",
            old_name="cpi",
            new_name="impressions",
        ),
        migrations.RenameField(
            model_name="sponsoredadimpression",
            old_name="cpi",
            new_name="impressions",
        ),
    ]
