# Generated by Django 4.1.4 on 2022-12-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_rename_cpi_searchadimpression_impressions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchadclicks",
            name="time_stamp",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="searchadimpression",
            name="time_stamp",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sponsoredadclicks",
            name="time_stamp",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sponsoredadimpression",
            name="time_stamp",
            field=models.DateField(auto_now_add=True),
        ),
    ]
