# Generated by Django 4.1.4 on 2023-01-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0010_alter_searchadclicks_clicks_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchadclicks",
            options={
                "ordering": ("created",),
                "verbose_name": "SearchAdClick",
                "verbose_name_plural": "SearchAdClicks",
            },
        ),
        migrations.AlterModelOptions(
            name="searchadimpression",
            options={
                "ordering": ("created",),
                "verbose_name": "SearchAdImpression",
                "verbose_name_plural": "SearchAdImpressions",
            },
        ),
        migrations.AlterModelOptions(
            name="sponsoredadclicks",
            options={
                "ordering": ("created",),
                "verbose_name": "SponsoredAdClick",
                "verbose_name_plural": "SponsoredAdClicks",
            },
        ),
        migrations.AlterModelOptions(
            name="sponsoredadimpression",
            options={
                "ordering": ("created",),
                "verbose_name": "SponsoredAdImpression",
                "verbose_name_plural": "SponsoredAdImpressions",
            },
        ),
        migrations.AlterField(
            model_name="searchadclicks",
            name="clicks",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="searchadimpression",
            name="impressions",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sponsoredadclicks",
            name="clicks",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sponsoredadimpression",
            name="impressions",
            field=models.IntegerField(null=True),
        ),
    ]
